### ISSUE TITLE
Solving environment: failed

### ISSUE THREAD

**Issue by kellisw** [Hammerling-Research-Group/dlq_py#1]
Following the instructions for installation and use of the dlq_py, I change my directory to the Desktop, clone the git repository, change my directory to dlq_py, and then run the `conda env create -f env.yml` command. I then get the following errors:

> Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (/Users/../anaconda3/lib/python3.11/site-packages/conda/plugins/types.py))
> Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (/Users/../anaconda3/lib/python3.11/site-packages/conda/plugins/types.py))
> WARNING conda.plugins.manager:load_entrypoints(114): Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (/Users/../anaconda3/lib/python3.11/site-packages/conda/plugins/types.py))
> WARNING conda.plugins.manager:load_entrypoints(114): Error while loading conda entry point: anaconda-cloud-auth (cannot import name 'ChannelAuthBase' from 'conda.plugins.types' (/Users/../anaconda3/lib/python3.11/site-packages/conda/plugins/types.py))
> Retrieving notices: ...working... done
> Collecting package metadata (repodata.json): done
> Solving environment: failed
> 
> ResolvePackageNotFound: 
>   - multiprocessing
>   - math
>   - os
>   - functools
>   - concurrent.futures
>   - traceback
>   - logging
>   - unittest
>   - pickle
>   - datetime

**Comment by pdwaggoner** [comment]
Thanks! Adding to the error log and will debug and get back here when we've solved it

**Comment by pdwaggoner** [comment]
Fixed in #3
